### ISSUE TITLE
affine.EPSILON is too big?

### ISSUE THREAD

**Issue by geowurster** [sgillies/affine#16]
I'm getting degenerate affine transformations for images with a very small cell size, like Landsat scenes in WGS84.  Is `1-e5` the default because it makes sense for mathematics?  I know there is a `set_epsilon()` function to manage this variable but wanted to get your thoughts about this before I dug deeper.

Here's an example of a Landsat scene going from UTM -> WGS84 for anyone else that might encounter this issue.  `Affine.determinant` and `affine.EPSILON` are used in `Affine.is_degenerate`.

cc/ @Yolandeezy

**Check the raw data**

```console
Captain:BAD kwurster$ rio insp LC80150332015197LGN00_B5.TIF 
Rasterio 0.25.0 Interactive Inspector (Python 2.7.10)
Type "src.meta", "src.read(1)", or "help(src)" for more information.
>>> src.affine
Affine(30.0, 0.0, 220485.0,
       0.0, -30.0, 4426815.0)
>>> ~src.affine
Affine(0.03333333333333333, 0.0, -7349.5,
       0.0, -0.03333333333333333, 147560.5)
>>> exit()
```

**Reproject to WGS84**

```console
Captain:BAD kwurster$ rio warp LC80150332015197LGN00_B5.TIF warped.tif --dst-crs EPSG:4326
```

**Check the reprojected data**

```console
Captain:BAD kwurster$ rio insp warped.tif 
Rasterio 0.25.0 Interactive Inspector (Python 2.7.10)
Type "src.meta", "src.read(1)", or "help(src)" for more information.
>>> src.affine
Affine(0.0003139959197432608, 0.0, -78.27163078313896,
       0.0, -0.0003139959197432608, 39.99035001263342)
>>> ~src.affine
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/affine/__init__.py", line 423, in __invert__
    "Cannot invert degenerate transform")
TransformNotInvertibleError: Cannot invert degenerate transform
>>> src.affine.determinant
-9.859343761541627e-08
>>> import affine
>>> affine.EPSILON
1e-05
```

**Comment by sgillies** [comment]
@geowurster do you mean [is EPSILON too big](https://github.com/sgillies/affine/blob/master/affine/__init__.py#L331)? If I read https://github.com/sgillies/affine/blob/master/affine/__init__.py#L61 right the default value is better for UTM, where units are 100s of thousands of meters, than for decimal degrees.

**Comment by geowurster** [comment]
@sgillies Yes, too big - that was a typo.  I found that note as well so I think higher res images in a geographic CRS just puts `a` and `e` outside the intended range.  Closing this and opening a ticket in rasterio for further discussion.
