### ISSUE TITLE
to/from World File order

### ISSUE THREAD

**Issue by perrygeo** [sgillies/affine#17]
Not sure if this really belongs here but in keeping with the spirit of `to_gdal` and `from_gdal` methods, it might be good to provide wrappers for the [World File](https://en.wikipedia.org/wiki/World_file) ordering: `a, d, b, e, c*, f*`

The only complication is that `c*` and `f*` refer to the center of the upper left cell so we'd need to pad them by 1/2 `a` and `e`.

**Comment by mwtoews** [comment]
See #11

**Comment by sgillies** [comment]
Thanks, @mwtoews, was just about to point to that. 

https://github.com/sgillies/affine/blob/master/CHANGES.txt#L11

**Comment by perrygeo** [comment]
Awesome! dump/load is even better
