### ISSUE TITLE
Warn or forbit left multiplication

### ISSUE THREAD

**Issue by Juanlu001** [sgillies/affine#32]
Because of how `__rmul__` is implemented, left multiplication can give surprising results:

```
>>> Affine.translation(1, 1) * Affine.scale(2, 3) * (1, 1)
(3.0, 4.0)
>>> (Affine.translation(1, 1) * Affine.scale(2, 3)) * (1, 1)
(3.0, 4.0)
>>> (1, 1) * Affine.translation(1, 1) * Affine.scale(2, 3)
(4.0, 6.0)
>>> (1, 1) * (Affine.translation(1, 1) * Affine.scale(2, 3))
(3.0, 4.0)
```

I think you already anticipated this:

https://github.com/sgillies/affine/blob/2.1.0/affine/__init__.py#L470-L472

However, Shapely `shapely.affinity.affine_transform` performs left multiplication and uses the GDAL order, so trying to mix these two can be a pain to get right. I think this should be at least document, but perhaps better raise a warning or even an exception.

**Comment by sgillies** [comment]
@Juanlu001 I agree, but this had better be for a 3.0 release (which I'll be happy to see).

**Comment by davidbrochart** [comment]
I'm not sure it is related, but I was surprised to see the following behavior:
```python
a = Affine(1, 0, 10, 0, -1, 20)

a * Affine.scale(2)
# Affine(2.0, 0.0, 10.0,
#        0.0, -2.0, 20.0)

Affine.scale(2) * a
# Affine(2.0, 0.0, 20.0,
#        0.0, -2.0, 40.0)
```

**Comment by davidbrochart** [comment]
Then I'm not using it right - I just wanted to cut the resolution by half.

**Comment by sgillies** [comment]
@davidbrochart increase the pixel size by 2 while preserving the origin? In that case to do it with matrix multiplication you need to translate to (0, 0), scale, and then translate back. It's probably easier to modify the matrix elements directly.

**Comment by davidbrochart** [comment]
Thanks!
