### ISSUE TITLE
Associativity in transform? 

### ISSUE THREAD

**Issue by ljwolf** [sgillies/affine#38]
Hi,

I've been working with the [GUF](https://urban-tep.eo.esa.int/geobrowser/?id=guf#!&context=GUFBinary%2F12m) recently, and have been making heavy uses of windows & transforms, so forgive me if this I'm just new or this is anticipated. 

I'm in a situation where I can make a view of the GUF (a 2.8 arcsecond global raster, here defined in a vrt)
```python
import rasterio as rio
handler = rio.open('/mnt/data/guf/GUF28_v2/GUF28_DLR_v01_global.vrt')
```
Then, build a window & read for Bristol, England:
```python
bristol_window = handler.window(-2.75,51.25,-2.25,51.75)
bristol_transform = handler.window_transform(bristol_window)
bristol = handler.read(window=bristol_window)
```
I do some `sklearn` magic to derive `labels_`, which gives an additional classification for each pixel
```python
labels_ = classifier.fit(bristol)
```
and was intending to map that alongside the bristol boundary, using the transforms:
```python
to_longlat = lambda row,col: (col,row) * bristol_transform * rio.Affine(.5,.5)
```
Applying this over my window gives me a slightly-incorrect adjustment:
![rasterio_transform_issue](https://user-images.githubusercontent.com/2250995/41050263-c2000aa8-69aa-11e8-8eaa-2d6d62a0ae3e.png)
but, switching to
```python
# force affine combination before hitting the row-col
to_longlat = lambda row,col: (col,row) * (bristol_transform * rio.Affine(.5,.5))
```
gives what I'm expecting. 
![rasterio_transform_ordered](https://user-images.githubusercontent.com/2250995/41050316-ecc335a8-69aa-11e8-8db7-15cf45cffb65.png)

Is this intentional? I usually expect `*` to be undirected and `@` to be directed, but maybe I'm just missing what's implied by multiplication here.

**Comment by ljwolf** [comment]
I guess this is strongly connected to #32, but demonstrate that this applies more generally than left vs. right multiplications?

**Comment by sgillies** [comment]
@ljwolf we don't support vectors on the left hand side of the multiplication. In a future version we're going to disallow it. If I read your intent correctly (I'm not sure why you're applying the scaling), I think your lambda should be this instead:

```to_longlat = lambda row, col: bristol_transform * rio.Affine(.5,.5) * (col, row)```

Unrelated: I'm trying to recommend against `import rasterio as rio` usage. Some of my coworkers do this and it makes it more difficult to run my static analysis tools on their code.

**Comment by ljwolf** [comment]
Great, thanks for the clarification! This makes sense. 

In that form, there's no associativity concern. 
```python
to_longlat = lambda row,col: (bristol_transform * rio.Affine(.5,.5))* (col, row)
to_longlat = lambda row,col: bristol_transform * rio.Affine(.5,.5) * (col,row)
```
are equivalent.

If `import rasterio as rio` isn't what you'd prefer, do you just prefer people use the full name, or is there another shortname you like? It's nice when we can write pedagogical stuff that matches the documentation's idiom.

**Comment by sgillies** [comment]
@ljwolf `import rasterio` and `from rasterio.module import Name` are the forms I'd like to see. Python's `import as` is best reserved for situations where we must avoid name clashes (https://www.python.org/dev/peps/pep-0221/).
