### ISSUE TITLE
Affine argument types - incorrect?

### ISSUE THREAD

**Issue by darrenleeweber** [sgillies/affine#45]
### versions

```
$ pip freeze | grep rasterio
rasterio==1.0.25
$ pip freeze | grep affine
affine==2.2.2
```

### typing issue

PyCharm warns that `Affine` expects a `List[float]` but it doesn't work that way, it works with individual `float` arguments (see screenshot attached).  Is the typing markup out of sync with the function arguments?

![Screen Shot 2019-08-28 at 4 09 53 PM](https://user-images.githubusercontent.com/240623/63898638-afa79a00-c9ae-11e9-97ae-4e82f32962f1.png)

Don't understand how PyCharm generates that warning from the class definition, maybe something related to this doc-string?
- https://github.com/sgillies/affine/blob/master/affine/__init__.py#L153

If an actual `List[float]` is provided, the `TypeError` is triggered because `len(members) == 1`

**Comment by sgillies** [comment]
@darrenleeweber strictly speaking, the Affine constructor takes a sequence of 6 floats. I don't remember why we're using `def __new__(cls, *members):` instead of `def __new__(cls, a, b, c, d, e, f):`. If the second form works, it would probably make PyCharm much more happy, yes?

**Comment by sgillies** [comment]
@darrenleeweber PR #46 looks promising. Any chance you could try it out? I'm not a PyCharm user and don't have space to start with it now.

**Comment by darrenleeweber** [comment]
LGTM and PyCharm seems to behave correctly with `test_pickle` hacks in screen-shot attached.

![Screen Shot 2019-09-04 at 11 15 44 AM](https://user-images.githubusercontent.com/240623/64280185-7a96cc80-cf05-11e9-9717-895b3376ded2.png)

**Comment by sgillies** [comment]
Thanks for the check @darrenleeweber !
