### ISSUE TITLE
Interoperability with shapely affinity module

### ISSUE THREAD

**Issue by loicdtx** [sgillies/affine#51]
Shapely's affinity module expects a tuple with the `(a, b, d, e, xoff, yoff)` order. I suggest adding a method to the `Affine` class to improve interoperability with shapely.
Let me know if that's an interesting proposal and I'll send a PR.

Loïc

**Comment by sgillies** [comment]
Sure, it would be welcome @loicdtx

**Comment by mwtoews** [comment]
Thanks for the PR! I should also note that the order used for shapely was based at the time on PostGIS' [ST_Affine](https://postgis.net/docs/ST_Affine.html), so this enhancement allows interoperability with PostGIS too.

**Comment by loicdtx** [comment]
Thanks for the explanation @mwtoews ! Would you then suggest a more 'generic' name than `.to_shapely` for the method?
Also, it looks like the the spatialite equivalent of ST_Affine is ATM_Transform.

**Comment by mwtoews** [comment]
Oh right, I see Spatialite's [ATM_Create](https://www.gaia-gis.it/gaia-sins/spatialite-sql-4.3.0.html#p15plus) constructor to build their integer-based AffineMatrix object, with the same order as PostGIS and shapely. Hmm, it's difficult to come up with a general name for this one, unlike `to_gdal`. Perhaps we should just keep it as `to_shapely` and just let the users see the documentation to determine if the coefficients are in the correct order.

**Comment by sgillies** [comment]
@loicdtx @mwtoews would `to_st_affine` be more generic?

**Comment by mwtoews** [comment]
I'd still prefer `to_shapely` to keep the term simple and within the Python realm of things. (Also, the ST_ prefix used by PostGIS generally means "spatial type", in case anyone is curious).

**Comment by jtbaker** [comment]
I'm working on a project now that this would be a handy abstraction to have. What about a compromise with an internal method that separate explicit method calls used as a pass-through, just so the naming is clear to the user? Would that be too bloated?

```
class Affine:
    ...

    def __to_st_affine(self):
        return (self.a, self.b, self.d, self.e, self.xoff, self.yoff)

    def to_shapely(self):
        return self.__to_st_affine()

    def to_postgis(self):
        return self.__to_st_affine()
```

**Comment by mwtoews** [comment]
@jtbaker the `master` branch has `to_shapely`, but I guess this hasn't made it to a release yet. If you really want to dabble with this feature, you can patch your code like this:
```python
from affine import Affine

if not hasattr(Affine, 'to_shapely'):
    def _to_shapely(self):
        return (self.a, self.b, self.d, self.e, self.xoff, self.yoff)
    Affine.to_shapely = _to_shapely
```

**Comment by jtbaker** [comment]
thanks for following up @mwtoews! I should have looked a little closer at the source here in the repo - I just sort of assumed since the method wasn't showing up in my fresh pop install, and this issue was still open that it wasn't in yet. I'll just install from source here on git for the time being.
