### ISSUE TITLE
Add `from_bounds` and `from_origin` class methods

### ISSUE THREAD

**Issue by geospatial-jeff** [sgillies/affine#55]
The `rasterio.transform` module has [several methods](https://github.com/mapbox/rasterio/blob/master/rasterio/transform.py#L99-L117) for generating an instance of `affine.Affine`.  I don't think these methods are specific to rasterio, and given that they just call `Affine` class methods, I think it would be useful to define these here.

If you think this is a good idea I'm happy to write up a PR!

**Comment by sgillies** [comment]
@geospatial-jeff thanks for the suggestion. I'm going to decline your offer because I want to keep this module free of GIS concepts like pixels and raster data georeferencing.
