### ISSUE TITLE
Why my metrix is rounded automatically

### ISSUE THREAD

**Issue by moopene36607** [sgillies/affine#62]
Why my metrix is rounded automatically?
```
print(Affine.rotation(45.0))
# I got:
# | 0.71,-0.71, 0.00|
# | 0.71, 0.71, 0.00|
# | 0.00, 0.00, 1.00|
```

**Comment by sgillies** [comment]
Only the string representation of the matrix is rounded: https://github.com/sgillies/affine/blob/master/affine/__init__.py#L296-L300.
